name: Fitness and Health Blog
description: We provide expert tips, workout routines, nutrition advice, and wellness inspiration to help you lead a balanced and active lifestyle.
theme: jekyll-theme-minimal
